### ISSUE TITLE
Fatal Python error: none_dealloc: deallocating None

### ISSUE THREAD

**Issue by AutoAuto** [LUCIT-Systems-and-Development/unicorn-binance-websocket-api#340] opened 2023-05-10 14:37 UTC
### Version of this library.

1.46.1

### Solution to Issue cannot be found in the documentation or other Issues and also occurs in the latest version of this library.

- [X] I checked the documentation and other Issues. I am using the latest version of this library.

### Hardware?

Local server/workstation

### Operating System?

Linux

### Python version?

Python3.10

### Installed packages

```shell
binance-connector~=1.8.0
configparser~=5.2.0
dnspython

requests~=2.27.1
PyJWT~=2.3.0
psutil
ujson
unicorn-fy
websocket-client
websockets==10.4
unicorn-binance-websocket-api~=1.46.1
mysql-connector-python~=8.0.32
python-dotenv~=0.19.2
```

### Logging output

```shell
05/10/2023 4:00:50 PM
Fatal Python error: none_dealloc: deallocating None
05/10/2023 4:00:50 PM
Python runtime state: initialized
05/10/2023 4:00:50 PM
05/10/2023 4:00:50 PM
Thread 0x00007fb2fe16d700 (most recent call first):
05/10/2023 4:00:50 PM
  File "/usr/local/lib/python3.10/site-packages/unicorn_binance_websocket_api/manager.py", line 808 in _keepalive_streams
05/10/2023 4:00:50 PM
  File "/usr/local/lib/python3.10/threading.py", line 946 in run
05/10/2023 4:00:50 PM
  File "/usr/local/lib/python3.10/threading.py", line 1009 in _bootstrap_inner
05/10/2023 4:00:50 PM
  File "/usr/local/lib/python3.10/threading.py", line 966 in _bootstrap
05/10/2023 4:00:50 PM
05/10/2023 4:00:50 PM
Thread 0x00007fb2fe96e700 (most recent call first):
05/10/2023 4:00:50 PM
  File "/usr/local/lib/python3.10/site-packages/unicorn_binance_websocket_api/manager.py", line 650 in _frequent_checks
05/10/2023 4:00:50 PM
  File "/usr/local/lib/python3.10/threading.py", line 946 in run
05/10/2023 4:00:50 PM
  File "/usr/local/lib/python3.10/threading.py", line 1009 in _bootstrap_inner
05/10/2023 4:00:50 PM
  File "/usr/local/lib/python3.10/threading.py", line 966 in _bootstrap
05/10/2023 4:00:50 PM
05/10/2023 4:00:50 PM
Current thread 0x00007fb301fab740 (most recent call first):
05/10/2023 4:00:50 PM
  File "/app/src/binance_ws/binance_kline.py", line 74 in update_whole_interval
05/10/2023 4:00:50 PM
  File "/app/src/binance_ws/binance_kline.py", line 45 in update_all_intervals
05/10/2023 4:00:50 PM
  File "/app/src/main.py", line 10 in <module>
05/10/2023 4:00:50 PM
05/10/2023 4:00:50 PM
Extension modules: websockets.speedups, regex._regex, markupsafe._speedups, ujson, psutil._psutil_linux, psutil._psutil_posix, _mysql_connector (total: 7)
```

### Processing method?

stream_buffer

### Used endpoint?

binance.com

### Issue

Issue reproducible after using unicorn lib and a loop to get kline data from Binance and also after using websocket userdata for account balance.

**Comment by oliver-zehentleitner** [comment] 2023-05-10 15:11
Script to reproduce and Logfile?

**Comment by AutoAuto** [comment] 2023-05-15 09:57
I can observe this problem before using unicorn lib, just importing it. My script is downloading Binance historical data using REST API https://api.binance.com/api/v3/klines?symbol=XXX, after that I will be using unicorn websocket to get update for all altocoinc from Binance but the crash occurred before I start using unicorn. Any ideas what I can do ? what to share ? I can reproduce the problem in 1-2 hours of using my script

**Comment by AutoAuto** [comment] 2023-05-26 13:42
@oliver-zehentleitner Do you use any C++ code in your modules ?

**Comment by oliver-zehentleitner** [comment] 2024-02-16 14:22
In version 1.46.1, the websockets sub-library uses a C++ Python extension.

Since 2.0.0, the entire UBS stack is available as a C++ Python extension.

In contrast to before, you no longer get source code wheels via PyPi and Conda but Cython binary wheels.

Since version 2 all modules are also free of Dataleaks.

Please test again, the problem should no longer exist.

If it does, please send me the command that causes the problem, preferably a whole script to test.

**Comment by oliver-zehentleitner** [comment] 2024-02-16 15:31
i'm closing this as it should be fixed. if you still have problems, just post here again and i'll reopen the issue.

**Closed by oliver-zehentleitner** 2024-02-16 15:31 UTC
Labels: bug
