### ISSUE TITLE
RuntimeError `error: 7` - error_msg: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by RichestSmoke** [LUCIT-Systems-and-Development/unicorn-binance-websocket-api#343] opened 2023-05-27 08:34 UTC
### Version of this library.

unicorn_fy: 0.12.2
unicorn_binance_local_depth_cache: not found
unicorn_binance_rest_api: 1.10.0
unicorn_binance_trailing_stop_loss: not found
unicorn_binance_websocket_api: 1.46.1

### Solution to Issue cannot be found in the documentation or other Issues and also occurs in the latest version of this library.

- [X] I checked the documentation and other Issues. I am using the latest version of this library.

### Hardware?

VPS or other cloud hosting

### Operating System?

Linux

### Python version?

Python3.10

### Installed packages

```shell
aiohttp                       3.8.4
aiosignal                     1.3.1
aniso8601                     9.0.1
async-timeout                 4.0.2
attrs                         22.1.0
Automat                       20.2.0
Babel                         2.8.0
bcrypt                        3.2.0
binance                       0.3
blinker                       1.6.2
certifi                       2022.6.15
chardet                       4.0.0
charset-normalizer            3.1.0
cheroot                       9.0.0
click                         8.1.3
cloud-init                    23.1.2
colorama                      0.4.5
command-not-found             0.3
configobj                     5.0.6
constantly                    15.1.0
cryptography                  3.4.8
dateparser                    1.1.8
dbus-python                   1.2.18
distro                        1.7.0
distro-info                   1.1+ubuntu1
Flask                         2.3.2
Flask-RESTful                 0.3.9
frozenlist                    1.3.3
httplib2                      0.20.4
hyperlink                     21.0.0
idna                          3.3
importlib-metadata            4.6.4
incremental                   21.3.0
itsdangerous                  2.1.2
jaraco.functools              3.6.0
jeepney                       0.8.0
Jinja2                        3.1.2
jsonpatch                     1.32
jsonpointer                   2.0
jsonschema                    4.6.0
keyring                       23.8.2
launchpadlib                  1.10.16
lazr.restfulclient            0.14.4
lazr.uri                      1.0.6
MarkupSafe                    2.1.2
more-itertools                8.10.0
multidict                     6.0.4
netifaces                     0.11.0
numpy                         1.24.3
oauthlib                      3.2.0
pandas                        2.0.1
pexpect                       4.8.0
pip                           22.2
psutil                        5.9.5
ptyprocess                    0.7.0
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycryptodome                  3.17
PyGObject                     3.42.2
PyHamcrest                    2.0.2
PyJWT                         2.4.0
pyOpenSSL                     21.0.0
pyparsing                     3.0.7
pyrsistent                    0.18.1
pyserial                      3.5
PySocks                       1.7.1
python-apt                    2.3.0+ubuntu2
python-binance                1.0.17
python-dateutil               2.8.2
python-debian                 0.1.46
python-magic                  0.4.26
pytz                          2022.2.1
PyYAML                        5.4.1
regex                         2023.5.5
requests                      2.27.1
SecretStorage                 3.3.3
service-identity              18.1.0
setuptools                    59.6.0
six                           1.16.0
sos                           4.4
ssh-import-id                 5.11
systemd-python                235
TA-Lib                        0.4.26
Twisted                       22.4.0
typing_extensions             4.5.0
tzdata                        2023.3
tzlocal                       5.0.1
ubuntu-advantage-tools        27.11.2
ufw                           0.36.1
ujson                         5.7.0
unattended-upgrades           0.1
unicorn-binance-rest-api      1.10.0
unicorn-binance-websocket-api 1.46.1
unicorn-fy                    0.12.2
urllib3                       1.26.9
wadllib                       1.3.6
websocket-client              1.5.1
websockets                    10.4
Werkzeug                      2.3.4
wheel                         0.37.1
yarl                          1.9.2
zipp                          1.0.0
zope.interface                5.4.0
```

### Logging output

```shell
BinanceWebSocketApiManager._create_stream_thread() stream_id=fdff9d9b93ae-aa46-5752-3d67-10d26e50  - RuntimeError `error: 7` - error_msg: maximum recursion depth exceeded - Please create an issue: https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/issues/new/choose
Exception in thread _create_stream_thread:  stream_id=fdff9d9b93ae-aa46-5752-3d67-10d26e50, time=1685008213.2401457:
Traceback (most recent call last):
  File "/root/binance_bot/three_candle.py", line 104, in process_new_receives_kline
    print(new_kline)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 170, in write
    self.write_and_convert(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 198, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 203, in write_plain_text
    self.wrapped.write(text[start:end])
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 170, in write
    self.write_and_convert(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 198, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 203, in write_plain_text
    self.wrapped.write(text[start:end])
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 170, in write
    self.write_and_convert(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 198, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 203, in write_plain_text
    self.wrapped.write(text[start:end])
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 170, in write
    self.write_and_convert(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 198, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 203, in write_plain_text
    self.wrapped.write(text[start:end])
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 170, in write
    self.write_and_convert(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 198, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 203, in write_plain_text
    self.wrapped.write(text[start:end])
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 170, in write
    self.write_and_convert(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 198, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 203, in write_plain_text
    self.wrapped.write(text[start:end])
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 170, in write
    self.write_and_convert(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 198, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 203, in write_plain_text
    self.wrapped.write(text[start:end])
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 170, in write
    self.write_and_convert(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 198, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 203, in write_plain_text
    self.wrapped.write(text[start:end])
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 170, in write
    self.write_and_convert(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 198, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 203, in write_plain_text
    self.wrapped.write(text[start:end])
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 170, in write
    self.write_and_convert(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 198, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 203, in write_plain_text
    self.wrapped.write(text[start:end])
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 170, in write
    self.write_and_convert(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 198, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 203, in write_plain_text
    self.wrapped.write(text[start:end])
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 170, in write
    self.write_and_convert(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 198, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 203, in write_plain_text
    self.wrapped.write(text[start:end])
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 170, in write
    self.write_and_convert(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 198, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 203, in write_plain_text
    self.wrapped.write(text[start:end])
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 170, in write
    self.write_and_convert(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 198, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 203, in write_plain_text
    self.wrapped.write(text[start:end])
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 170, in write
    self.write_and_convert(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 198, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 203, in write_plain_text
    self.wrapped.write(text[start:end])
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 170, in write
    self.write_and_convert(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 198, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 203, in write_plain_text
    self.wrapped.write(text[start:end])
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 170, in write
    self.write_and_convert(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 198, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 203, in write_plain_text
    self.wrapped.write(text[start:end])BinanceWebSocketApiManager._frequent_checks() - High CPU usage since 5 seconds: 100.0
Exception in thread 
frequent_checks:
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 47, in write
Traceback (most recent call last):
      File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
self.__convertor.write(text)    
self.run()  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 170, in write

      File "/usr/lib/python3.10/threading.py", line 953, in run
self.write_and_convert(text)    
self._target(*self._args, **self._kwargs)  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 198, in write_and_convert

      File "/usr/local/lib/python3.10/dist-packages/unicorn_binance_websocket_api/manager.py", line 664, in _frequent_checks
self.write_plain_text(text, cursor, len(text))    
logger.warning(f"BinanceWebSocketApiManager._frequent_checks() - High CPU usage since "  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 203, in write_plain_text

      File "/usr/lib/python3.10/logging/__init__.py", line 1489, in warning
self.wrapped.write(text[start:end])    
self._log(WARNING, msg, args, **kwargs)  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 47, in write

      File "/usr/lib/python3.10/logging/__init__.py", line 1624, in _log
self.__convertor.write(text)    
self.handle(record)  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 170, in write
    
  File "/usr/lib/python3.10/logging/__init__.py", line 1634, in handle
self.write_and_convert(text)    
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 198, in write_and_convert
self.callHandlers(record)    
  File "/usr/lib/python3.10/logging/__init__.py", line 1704, in callHandlers
self.write_plain_text(text, cursor, len(text))
    lastResort.handle(record)  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 203, in write_plain_text

      File "/usr/lib/python3.10/logging/__init__.py", line 968, in handle
self.wrapped.write(text[start:end])    
self.emit(record)  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 47, in write

      File "/usr/lib/python3.10/logging/__init__.py", line 1103, in emit
self.__convertor.write(text)
    stream.write(msg + self.terminator)  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 170, in write

      File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 47, in write
self.write_and_convert(text)    
self.__convertor.write(text)  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 198, in write_and_convert

      File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 170, in write
self.write_plain_text(text, cursor, len(text))
    self.write_and_convert(text)  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 203, in write_plain_text

      File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 198, in write_and_convert
self.wrapped.write(text[start:end])    
self.write_plain_text(text, cursor, len(text))  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 47, in write

      File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 203, in write_plain_text
self.__convertor.write(text)    
self.wrapped.write(text[start:end])  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 170, in write

      File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 47, in write
self.write_and_convert(text)    
self.__convertor.write(text)  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 198, in write_and_convert

      File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 170, in write
self.write_plain_text(text, cursor, len(text))    
self.write_and_convert(text)  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 203, in write_plain_text

      File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 198, in write_and_convert
self.wrapped.write(text[start:end])    
self.write_plain_text(text, cursor, len(text))  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 47, in write

      File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 203, in write_plain_text
self.__convertor.write(text)    
self.wrapped.write(text[start:end])  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 170, in write

      File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 47, in write
self.write_and_convert(text)    
self.__convertor.write(text)  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 198, in write_and_convert

      File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 170, in write
self.write_plain_text(text, cursor, len(text))    
self.write_and_convert(text)  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 203, in write_plain_text

      File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 198, in write_and_convert
self.wrapped.write(text[start:end])
    self.write_plain_text(text, cursor, len(text))  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 47, in write

      File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 203, in write_plain_text
self.__convertor.write(text)    
self.wrapped.write(text[start:end])  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 170, in write
    
self.write_and_convert(text)  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 47, in write

      File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 198, in write_and_convert
self.__convertor.write(text)    
self.write_plain_text(text, cursor, len(text))  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 170, in write

      File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 203, in write_plain_text
self.write_and_convert(text)    
self.wrapped.write(text[start:end])  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 198, in write_and_convert

  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 47, in write
    self.write_plain_text(text, cursor, len(text))    
self.__convertor.write(text)  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 203, in write_plain_text

      File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 170, in write
self.wrapped.write(text[start:end])    
self.write_and_convert(text)  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 47, in write

      File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 198, in write_and_convert
self.__convertor.write(text)    
self.write_plain_text(text, cursor, len(text))  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 170, in write

      File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 203, in write_plain_text
self.write_and_convert(text)    
self.wrapped.write(text[start:end])  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 198, in write_and_convert

      File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 47, in write
self.write_plain_text(text, cursor, len(text))    
self.__convertor.write(text)  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 203, in write_plain_text

  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 170, in write
    self.wrapped.write(text[start:end])    
self.write_and_convert(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 47, in write
      File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 198, in write_and_convert
    self.__convertor.write(text)self.write_plain_text(text, cursor, len(text))

  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 170, in write
      File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 203, in write_plain_text
self.write_and_convert(text)    
self.wrapped.write(text[start:end])  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 198, in write_and_convert
```

### Processing method?

process_stream_data

### Used endpoint?

binance.com-futures

### Issue

the script worked without errors for almost two days and then an error popped up RuntimeError `error: 7` - error_msg: maximum recursion depth exceeded
part of my code:

`def get_historical_klines (ticker):
    df = pd.DataFrame(my_client.futures_historical_klines(ticker, '5m', '17 hours ago UTC', 'now UTC'))
    df = df.drop([6, 7, 8, 9, 10, 11], axis=1)
    df.columns = ['Time', 'Open', 'High', 'Low', 'Close', 'Volume']
    df = df.astype(float)
    return df

df = get_historical_klines(COIN)
os.environ['SSL_CERT_FILE'] = certifi.where()
binance_websocket_api_manager = BinanceWebSocketApiManager(exchange="binance.com-futures")
def process_new_receives_kline(stream_data, stream_buffer_name=False):
    global df
    global new_kline
    stream_data = json.loads(stream_data)
    try:
        stream_data = stream_data['data']['k']
        if stream_data['x'] == True:
            new_kline = {'Time' : float(stream_data['T']), 'Open' : float(stream_data['o']), 'High' : float(stream_data['h']), 
                        'Low' : float(stream_data['l']), 'Close' : float(stream_data['c']), 'Volume' : float(stream_data['v'])}
            print(new_kline)
            df.loc[len(df)] = new_kline
            sma_30 = talib.SMA(df['Close'], timeperiod=30)
            rsi = talib.RSI(df['Close'], 14)
            df['SMA_30'] = sma_30
            df['RSI'] = rsi

            if len(df) > 200:
                df = df.drop(df.index[0])
                df = df.reset_index(drop=True)
            print(df)
    except:
        print('Stream kline does not work or did not have time to start')
        traceback.print_exc()
binance_websocket_api_manager.create_stream(["kline_5m"], COIN.lower(), process_stream_data=process_new_receives_kline)`

**Comment by AutoAuto** [comment] 2023-06-23 07:41
@oliver-zehentleitner I can also observe this issue on my scripts, after 2-3 days of activity. Any hints what can cause this problem ? Im not using colorama in my code

**Comment by gbozee** [comment] 2023-06-28 19:54
Ran into the same issue. The `disable_colorama` flag isn't forwarded down to `BinanceRestApiManager` instance used by the `BinanceWebSocketApiRestclient` class.

I noticed the `BinanceRestApiManager` class resides [here](https://github.com/LUCIT-Systems-and-Development/unicorn-binance-rest-api) which is where I think the fix would be.

**Comment by oliver-zehentleitner** [comment] 2023-10-16 17:48
duplicate of https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/issues/338

> Ran into the same issue. The `disable_colorama` flag isn't forwarded down to `BinanceRestApiManager` instance used by the `BinanceWebSocketApiRestclient` class.
> 
> I noticed the `BinanceRestApiManager` class resides [here](https://github.com/LUCIT-Systems-and-Development/unicorn-binance-rest-api) which is where I think the fix would be.

thanks i add this also to the todo list.

**Closed by oliver-zehentleitner** 2023-10-16 17:48 UTC
Labels: bug, duplicate
