### ISSUE TITLE
BinanceWebSocketApiManager._create_stream_thread() stream_id=7bb5ef452f01-7200-c1f7-310c-f7e4ee8e  - RuntimeError `error: 11` - error_msg:  cannot schedule new futures after interpreter shutdown

### ISSUE THREAD

**Issue by WJ-Thanefield** [LUCIT-Systems-and-Development/unicorn-binance-websocket-api#299] opened 2022-12-19 23:14 UTC
### Version of this library.

Latest

### Solution to Issue cannot be found in the documentation or other Issues and also occurs in the latest version of this library.

- [X] I checked the documentation and other Issues. I am using the latest version of this library.

### Hardware?

Local server/workstation

### Operating System?

Windows

### Python version?

Python3.9

### Processing method?

stream_buffer

### Used endpoint?

binance.com

### Issue

BinanceWebSocketApiManager.stream_is_crashing(7bb5ef452f01-7200-c1f7-310c-f7e4ee8e)
BinanceWebSocketApiManager._create_stream_thread() stream_id=7bb5ef452f01-7200-c1f7-310c-f7e4ee8e  - RuntimeError `error: 11` - error_msg:  cannot schedule new futures after interpreter shutdown - Please create an issue: https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/issues/new/choose

**Comment by oliver-zehentleitner** [comment] 2022-12-20 11:46
Thank you! We need log files and a script to reproduce the error...

**Comment by WJ-Thanefield** [comment] 2022-12-20 12:40
Thanks Oliver, this time I did not manage to produce a log file. But once I encounter it again will send the log file here. Thanks again.

**Comment by AnimusXCASH** [comment] 2022-12-29 16:22
@oliver-zehentleitner I am getting same error. 

Is there anyway how it can be handled with exceptions? 

```BinanceWebSocketApiSocket.start_socket(4e0592aab0ff-03ed-5592-8b4d-a54234ae, ['kline_1m'], ['hookusdt']) - Exception ConnectionClosed - error_msg: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
BinanceWebSocketApiManager.stream_is_crashing(4e0592aab0ff-03ed-5592-8b4d-a54234ae)
BinanceWebSocketApiManager._create_stream_thread() stream_id=4e0592aab0ff-03ed-5592-8b4d-a54234ae  - RuntimeError `error: 11` - error_msg:  cannot schedule new futures after interpreter shutdown - Please create an issue: 
```

Ill try to log it and post what i get out

**Comment by oliver-zehentleitner** [comment] 2022-12-30 16:52
Hello!

Affected lines of code: 
https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/blob/master/unicorn_binance_websocket_api/manager.py#L529

Script to replicate (Thanks to [nhmartens](https://github.com/nhmartens)):
https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/files/10300596/error_replication_v01.txt

Same issues:
https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/issues/282, https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/issues/297, https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/issues/299


I know and understand this issue, but when we get in touch with it the first time (https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/issues/131) it happened also in other code parts which was very easy to reproduce within seconds and i did not want to "over fix it" with code parts that may be not necessary to solve it. I thought its possible that since we fixed it in https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/issues/131 i could also avoid it here in this code block.

To implement a CLEAN solution i would need one log file in INFO or even DEBUG logging mode... to see what exactly is happening inside ubwa before the exception occurs. 

If you gives give me such a log file, i will start updating it on 2.1.2023 and prepare a fixed release.

**Comment by nhmartens** [comment] 2023-01-01 16:04
This is the log file of my replication run, I hope this helps.

[error_replication.py.log.zip](https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/files/10329063/error_replication.py.log.zip)

**Comment by nhmartens** [comment] 2023-01-24 22:21
@oliver-zehentleitner is there any update on this? Is the log file I provided what you were looking for or do you need anything else?

**Comment by oliver-zehentleitner** [comment] 2023-03-04 02:11
I will pick this up at next, but i get to tired for this now :/

**Comment by dima-dmytruk23** [comment] 2023-03-19 09:06
Up plz

**Comment by rockyrobinls29** [comment] 2023-03-20 12:13
Does anyone have any suggestions for a temporary fix for this until it gets resolved?

**Comment by oliver-zehentleitner** [comment] 2023-03-20 13:08
i should be able to find the time today or tomorrow. i will get back to you with the update.

**Comment by rockyrobinls29** [comment] 2023-03-20 14:09
Thank you! Your work is very much appreciated 😎

**Comment by oliver-zehentleitner** [comment] 2023-03-21 19:57
tomorrow, sorry, was too busy today :/

**Comment by oliver-zehentleitner** [comment] 2023-03-24 13:36
This error message occurs when a shutdown process has been initiated by the Python interpreter. 

This means that the interpreter is about to exit, and thus cannot accept any new tasks.

This happens when `exit()`/`quit()` or similar are called, the program window is closed or when the main thread is terminated. Therefore `create_stream()` is also blocking if no "high_performance=True" is activated. This is how we got a handle on the problem here: https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/issues/131.

I can't replicate the problem so far.

I don't know if it's possible to start new threads again after this error, doesn't sound like it actually. 

Basically, I also find that when the shutdown process is initiated, the code does exactly what it is supposed to. it shuts down UBWA cleanly and exits.

So the problem must/should be solved in the program logic.

Does this code work for you and avoid the error?

```
from unicorn_binance_websocket_api import BinanceWebSocketApiManager
import asyncio
import logging
import os

logging.getLogger("unicorn_binance_websocket_api")
logging.basicConfig(level=logging.DEBUG,
                    filename=os.path.basename(__file__) + '.log',
                    format="{asctime} [{levelname:8}] {process} {thread} {module}: {message}",
                    style="{")

class Test:
    def __init__(self, apikey, apisecret):
        self.apikey = apikey
        self.apisecret = apisecret
        self.ubwa = None

    async def start(self):
        def handle_socket_message(data):
            print(f"msg: {data}")

        self.ubwa = BinanceWebSocketApiManager(exchange='binance.com-margin', output_default='dict')
        self.ubwa.create_stream(["arr"], ["!userData"], process_stream_data=handle_socket_message,
                                api_key=self.apikey, api_secret=self.apisecret)
        print('Started')

        while True:
            await asyncio.sleep(1)


if __name__ == "__main__":
    test = Test("key", "sec")
    try:
        asyncio.run(test.start())
    except KeyboardInterrupt:
        print("Gracefully stopping the websocket manager...")
        test.ubwa.stop_manager_with_all_streams()
```

**Comment by oliver-zehentleitner** [comment] 2023-03-24 14:07
Actually a simple 

```
while True:
    time.sleep(1)
```

should fix this issue... have you ever tryed?

**Comment by dima-dmytruk23** [comment] 2023-03-24 14:29
> Actually a simple
> 
> ```
> while True:
>     time.sleep(1)
> ```
> 
> at the end of your script (before it finishs) should fix this issue... have you ever tryed?

Not works

[logs](https://gist.github.com/dima-dmytruk23/3da3c0a245dd8a0b5af0a36394bba0fa)

**Comment by nhmartens** [comment] 2023-03-24 15:14
> Actually a simple
> 
> ```
> while True:
>     time.sleep(1)
> ```
> 
> at the end of your script (before it finishs) should fix this issue... have you ever tryed?

I also tried this, and it did not solve the issue for me.

**Comment by nhmartens** [comment] 2023-03-24 15:17
> Hello!
> 
> Affected lines of code: https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/blob/master/unicorn_binance_websocket_api/manager.py#L529
> 
> Script to replicate (Thanks to [nhmartens](https://github.com/nhmartens)): https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/files/10300596/error_replication_v01.txt
> 
> Same issues: #282, #297, #299
> 
> I know and understand this issue, but when we get in touch with it the first time (#131) it happened also in other code parts which was very easy to reproduce within seconds and i did not want to "over fix it" with code parts that may be not necessary to solve it. I thought its possible that since we fixed it in #131 i could also avoid it here in this code block.
> 
> To implement a CLEAN solution i would need one log file in INFO or even DEBUG logging mode... to see what exactly is happening inside ubwa before the exception occurs.
> 
> If you gives give me such a log file, i will start updating it on 2.1.2023 and prepare a fixed release.

The script mentioned here replicates the error for me. However, it usually takes between two and four days until the issue occurs and the script exits.

**Comment by oliver-zehentleitner** [comment] 2023-03-24 16:09
> > Hello!
> > Affected lines of code: https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/blob/master/unicorn_binance_websocket_api/manager.py#L529
> > Script to replicate (Thanks to [nhmartens](https://github.com/nhmartens)): https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/files/10300596/error_replication_v01.txt
> > Same issues: #282, #297, #299
> > I know and understand this issue, but when we get in touch with it the first time (#131) it happened also in other code parts which was very easy to reproduce within seconds and i did not want to "over fix it" with code parts that may be not necessary to solve it. I thought its possible that since we fixed it in #131 i could also avoid it here in this code block.
> > To implement a CLEAN solution i would need one log file in INFO or even DEBUG logging mode... to see what exactly is happening inside ubwa before the exception occurs.
> > If you gives give me such a log file, i will start updating it on 2.1.2023 and prepare a fixed release.
> 
> The script mentioned here replicates the error for me. However, it usually takes between two and four days until the issue occurs and the script exits.

I used it and shorted it, then i added a possible fix - this is the result: https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/issues/299#issuecomment-1482809641

Please can you test it?

**Comment by dima-dmytruk23** [comment] 2023-03-24 16:36
> > > However, it usually takes between two and four days until the issue occurs and the script exits.
> > 
> > 
> > You don't have to wait a few days. You can reproduce the bug by throwing an `websockets.exceptions.ConnectionClosed` exception to `start_socket` method of the `BinanceWebSocketApiSocket` somewhere around this place https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/blob/master/unicorn_binance_websocket_api/sockets.py#L116
> 
> Please test [#299 (comment)](https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/issues/299#issuecomment-1482809641) with the latest and unmodified lib version.
> 
> In your simulation of the bug, can you set this to `False`: https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/blob/77f2f7294b4b5d7fe21bcda50eb7c8e1beb41f10/unicorn_binance_websocket_api/sockets.py#LL73C45-L73C45
> 
> And tell me what then happens?

OK. I updated version to 1.42.0 and set `self.manager.socket_is_ready[self.stream_id] = False` - same log as above I sent

**Comment by dima-dmytruk23** [comment] 2023-03-24 16:44
> > > However, it usually takes between two and four days until the issue occurs and the script exits.
> > 
> > 
> > You don't have to wait a few days. You can reproduce the bug by throwing an `websockets.exceptions.ConnectionClosed` exception to `start_socket` method of the `BinanceWebSocketApiSocket` somewhere around this place https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/blob/master/unicorn_binance_websocket_api/sockets.py#L116
> 
> Please test [#299 (comment)](https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/issues/299#issuecomment-1482809641) with the latest and unmodified lib version.
> 
> In your simulation of the bug, can you set this to `False`: https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/blob/77f2f7294b4b5d7fe21bcda50eb7c8e1beb41f10/unicorn_binance_websocket_api/sockets.py#LL73C45-L73C45
> 
> And tell me what then happens?


It seems updating to version 1.42.0 solved the problem and setting `self.manager.socket_is_ready[self.stream_id] = False` solved the problem.

**Comment by dima-dmytruk23** [comment] 2023-03-24 16:44
Is it worth waiting for a fix inside the library?

**Comment by oliver-zehentleitner** [comment] 2023-03-24 16:54
We easily could add a flag to bypass "self.manager.socket_is_ready[self.stream_id] = True". So a fix would be pretty easy. But adding this has also a downside, becouse now you have an unlimited blocking create_stream() function isnt it?

And i really beflief its fixed on the wrong end.... i bet that now also a code structure similar to https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/issues/299#issuecomment-1482809641 fixes the problem.

**Comment by dima-dmytruk23** [comment] 2023-03-24 16:59
> But adding this has also a downside, becouse now you have an unlimited blocking create_stream() function isnt it?

Maybe add it to `__init__` ?

**Comment by oliver-zehentleitner** [comment] 2023-03-24 17:02
> > И я действительно верю, что это исправлено не на том конце... Держу пари, что теперь также структура кода, подобная [# 299 (комментарий),](https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/issues/299#issuecomment-1482809641) устраняет проблему.
> 
> No, I didn't even use `while True: sleep(1)`, but the problem is solved)

Ok, but the framework I provided in https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/issues/299#issuecomment-1482809641 is maybe the smarter way than hacking the lib 😄

**Comment by dima-dmytruk23** [comment] 2023-03-24 17:16
> > > И я действительно верю, что это исправлено не на том конце... Держу пари, что теперь также структура кода, подобная [# 299 (комментарий),](https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/issues/299#issuecomment-1482809641) устраняет проблему.
> > 
> > 
> > No, I didn't even use `while True: sleep(1)`, but the problem is solved)
> 
> Ok, but the framework I provided in [#299 (comment)](https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/issues/299#issuecomment-1482809641) is maybe the smarter way than hacking the lib 😄

Agreed, but the `while True: sleep(1)` solution seems very dirty too

**Comment by oliver-zehentleitner** [comment] 2023-03-25 10:23
I also prefer:
```
        while True:
            await asyncio.sleep(1)
```

**Comment by oliver-zehentleitner** [comment] 2023-03-26 19:33
I leave this for now as it is and wait for more feedback of the community...

**Comment by oliver-zehentleitner** [comment] 2023-04-03 19:30
any news, did my suggestion solve your issues?

**Comment by dima-dmytruk23** [comment] 2023-04-03 23:10
> any news, did my suggestion solve your issues?

Yes, for more than a week about 10 stages have been working continuously.

**Comment by oliver-zehentleitner** [comment] 2023-04-03 23:41
Cool. Then i will close this. Reopen if needed. Thanks!

**Closed by oliver-zehentleitner** 2023-04-03 23:41 UTC
Labels: bug, enhancement, info
