### ISSUE TITLE
Unhandled exception futures.TimeoutError()

### ISSUE THREAD

**Issue by am11y** [LUCIT-Systems-and-Development/unicorn-binance-websocket-api#221] opened 2021-11-29 18:48 UTC
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [x] Are you using the module on a VPS or other Cloud hosting?
- [ ] Are you using the module on a Raspberry Pi?

#### What kind of internet connection do you have?
```
Optics.
```

#### Average system load (CPU)
```
6 × AMD EPYC 7282 16-Core Processor
10% avg load
```

#### Hardware specification 
```
Include here a description of the server hardware.
```

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux : Debian GNU/Linux 10

#### Options
- [x] stream_buffer
- [ ] process_stream_data

#### Which endpoint do you connect?
```
binance.com-futures
```

#### Python Version Requirement
- [x] I am using Python 3.7 or above

#### Exact Python Version?
```
3.7.3
```

#### Pip Version?
```
18.1
```

#### Dependencies
https://pastebin.com/6uDicgT9

#### UNICORN Binance WebSocket API Version?
```
1.34.2
```

#### Description of your issue
```
I get the exceptions below on regular basis, many times consecutively in a row:
```

```
Exception in thread Thread-1800:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.7/site-packages/unicorn_binance_websocket_api/unicorn_binance_websocket_api_manager.py", line 473, in _create_stream_thread
    loop.run_until_complete(socket.start_socket())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/user/.local/lib/python3.7/site-packages/unicorn_binance_websocket_api/unicorn_binance_websocket_api_socket.py", line 68, in start_socket
    symbols=self.symbols) as websocket:
  File "/home/user/.local/lib/python3.7/site-packages/unicorn_binance_websocket_api/unicorn_binance_websocket_api_connection.py", line 147, in __aenter__
    self.manager.websocket_list[self.stream_id] = await self._conn.__aenter__()
  File "/home/user/.local/lib/python3.7/site-packages/websockets/legacy/client.py", line 632, in __aenter__
    return await self
  File "/home/user/.local/lib/python3.7/site-packages/websockets/legacy/client.py", line 649, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 423, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

```

**Comment by am11y** [comment] 2021-12-01 19:27
Hello, anybody here? I get this error constantly and it is very annoying. Does it happen to anyone else too? What should be done to fix it?

**Comment by oliver-zehentleitner** [comment] 2021-12-01 20:10
In old python versions i never had that issue in 2 years.

We have similar new open issues related to this issue.

Please add answers to the questions we ask when you created this new issue. This information help me to solve this issue.

I am planing a bigger release at the end of this year with a fix for this bug.

**Comment by am11y** [comment] 2021-12-01 20:47
> Please add answers to the questions

Fixed

**Comment by oliver-zehentleitner** [comment] 2021-12-01 20:49
stream_buffer or process_stream_data?

**Comment by am11y** [comment] 2021-12-01 21:19
Sorry, I don't know what is this.
Here is the initialization code for stream:


```
self.__socket_manager_fapi = BinanceWebSocketApiManager( exchange = "binance.com-futures" )
                # self.__stream_id = None
                self.__fapi_thread = threading.Thread( target = self.__callback_message, args = ( self.__socket_manager_fapi, callbacks_fapi, ) )
                self.__fapi_thread.start()
```

**Comment by oliver-zehentleitner** [comment] 2021-12-01 21:21
Then you use the stream_buffer! Thanks, this infos help!

**Comment by am11y** [comment] 2021-12-01 21:23
Could you please point me to the docs which explain what is the difference between  stream_buffer //  process_stream_data ?

**Comment by oliver-zehentleitner** [comment] 2021-12-01 21:31
stream_buffer info: https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/wiki/%60stream_buffer%60

process_stream_data is a call_back solution: https://oliver-zehentleitner.github.io/unicorn-binance-websocket-api/unicorn_binance_websocket_api.html?highlight=process_stream_data (just scroll down a bit to the description of the parameters)

**Comment by am11y** [comment] 2021-12-07 09:30
Hello Oliver,
this problem completely destroys my application. I get spammed with these errors and stream is unusable. Could you please point out to which version of unicorn-bn-websocket package should I revert? Perhaps to the one that does not use async.io? How can I temporarily avoid this until your fix is ready?
Thanks.

**Comment by oliver-zehentleitner** [comment] 2021-12-07 12:34
Hello!

I understand your problem and your needs, i am just very busy atm :/

I think the queue of awaits is getting to long and then timeouting. How many subscriptions do you have?

You must know, Python is really cool, but it sucks with concurrency, even if you have 6 cpu sockets, each with 16 cores. You just use the resources of one cpu core. Read here about the reason: https://realpython.com/python-gil/

I wanted to study your log file, but did not find it. Wasnt it already posted?

Your python version is well tested with UBWA, i guess the root cause for the error you get is an overloaded application.

I can release a fix to reconnect, but you would still not be stable in cause of all the unneccessary reconnects.

**Comment by am11y** [comment] 2021-12-07 16:05
I have ~50 different streams.

That's why I asked this question: https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/issues/220

Is it of any use if I try to pack these 50 subscriptions in single stream?

So there is no old version that I can fall back to in order to rescue the situation temporarily?

**Comment by am11y** [comment] 2021-12-08 08:52
Here is the log file:
https://pastebin.com/AfSTmYiQ

**Comment by oliver-zehentleitner** [comment] 2021-12-08 20:41
The link does not work. you can drag&drop the log file to the text box of a new comment.

**Comment by oliver-zehentleitner** [comment] 2021-12-08 21:10
You have 50 streams with one subscription each? If yes, make one stream for each channel like trade, kline_1m, ... and use them for up to 1024 subscriptions per stream. Futures is 200 subscriptions per stream: https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/wiki/Binance-websocket-endpoint-configuration-overview

**Comment by am11y** [comment] 2021-12-08 22:24
Let's try again:

https://pastebin.com/sHMnQ8HA

**Closed** 2022-01-04 15:57 UTC

**Comment by oliver-zehentleitner** [comment] 2022-01-04 16:05
Its released https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/releases/tag/1.35.0
